# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'three.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(855, 730)
        font = QtGui.QFont()
        font.setPointSize(11)
        Form2.setFont(font)
        self.widget = QtWidgets.QWidget(Form2)
        self.widget.setGeometry(QtCore.QRect(160, 140, 118, 86))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Slider = Slider(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Slider.setFont(font)
        self.Slider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Slider.setProperty("value", 0)
        self.Slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider.setTickInterval(0)
        self.Slider.setObjectName("Slider")
        self.horizontalLayout_2.addWidget(self.Slider)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.SplitToolButton = SplitToolButton(Form2)
        self.SplitToolButton.setGeometry(QtCore.QRect(185, 84, 71, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SplitToolButton.sizePolicy().hasHeightForWidth())
        self.SplitToolButton.setSizePolicy(sizePolicy)
        self.SplitToolButton.setObjectName("SplitToolButton")
        self.SwitchButton = SwitchButton(Form2)
        self.SwitchButton.setGeometry(QtCore.QRect(260, 82, 84, 37))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SwitchButton.sizePolicy().hasHeightForWidth())
        self.SwitchButton.setSizePolicy(sizePolicy)
        self.SwitchButton.setObjectName("SwitchButton")
        self.ComboBox = ComboBox(Form2)
        self.ComboBox.setGeometry(QtCore.QRect(102, 84, 77, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox.sizePolicy().hasHeightForWidth())
        self.ComboBox.setSizePolicy(sizePolicy)
        self.ComboBox.setText("")
        self.ComboBox.setObjectName("ComboBox")

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "Form"))
        self.SwitchButton.setText(_translate("Form2", "关闭"))
        self.SwitchButton.setOnText(_translate("Form2", "打开"))
        self.SwitchButton.setOffText(_translate("Form2", "关闭"))
from qfluentwidgets import ComboBox, Slider, SplitToolButton, SwitchButton
