# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'two.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(855, 730)
        font = QtGui.QFont()
        font.setPointSize(11)
        Form2.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavigationInterface = NavigationInterface(Form2)
        self.NavigationInterface.setObjectName("NavigationInterface")
        self.horizontalLayout.addWidget(self.NavigationInterface)
        self.LineEdit = LineEdit(Form2)
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout.addWidget(self.LineEdit)

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "Form"))
from qfluentwidgets import LineEdit, NavigationInterface
