# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'one.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(715, 606)
        font = QtGui.QFont()
        font.setPointSize(11)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/icons/win_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("")
        self.pushButton = PushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 0, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.cBox = QtWidgets.QCheckBox(Form)
        self.cBox.setGeometry(QtCore.QRect(50, 70, 91, 21))
        self.cBox.setChecked(True)
        self.cBox.setObjectName("cBox")
        self.cBox_2 = QtWidgets.QCheckBox(Form)
        self.cBox_2.setGeometry(QtCore.QRect(60, 40, 71, 21))
        self.cBox_2.setObjectName("cBox_2")
        self.label_img = QtWidgets.QLabel(Form)
        self.label_img.setGeometry(QtCore.QRect(220, 0, 381, 301))
        self.label_img.setStyleSheet("")
        self.label_img.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img.setText("")
        self.label_img.setScaledContents(False)
        self.label_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img.setWordWrap(False)
        self.label_img.setObjectName("label_img")
        self.open_img = QtWidgets.QPushButton(Form)
        self.open_img.setGeometry(QtCore.QRect(610, 10, 101, 31))
        self.open_img.setObjectName("open_img")
        self.lineEdit = LineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(320, 320, 131, 33))
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(60, 190, 81, 192))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.open_win2 = QtWidgets.QPushButton(Form)
        self.open_win2.setGeometry(QtCore.QRect(40, 100, 101, 31))
        self.open_win2.setObjectName("open_win2")
        self.close_win2 = QtWidgets.QPushButton(Form)
        self.close_win2.setGeometry(QtCore.QRect(40, 140, 101, 31))
        self.close_win2.setObjectName("close_win2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(210, 360, 91, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.ListWidget = ListWidget(Form)
        self.ListWidget.setGeometry(QtCore.QRect(130, 400, 61, 192))
        self.ListWidget.setObjectName("ListWidget")
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        self.SearchLineEdit = SearchLineEdit(Form)
        self.SearchLineEdit.setGeometry(QtCore.QRect(200, 410, 187, 33))
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.emitS = PrimaryPushButton(Form)
        self.emitS.setGeometry(QtCore.QRect(210, 460, 153, 32))
        self.emitS.setObjectName("emitS")

        self.retranslateUi(Form)
        self.cBox.toggled['bool'].connect(self.pushButton.setVisible) # type: ignore
        self.cBox.toggled['bool'].connect(self.cBox_2.setChecked) # type: ignore
        self.SearchLineEdit.textChanged['QString'].connect(self.lineEdit.setText) # type: ignore
        self.SearchLineEdit.textChanged['QString'].connect(Form.setWindowTitle) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "第一个基于PyQt5的桌面应用"))
        self.pushButton.setText(_translate("Form", "关闭窗口"))
        self.cBox.setText(_translate("Form", "显示/隐藏"))
        self.cBox_2.setText(_translate("Form", "不可用"))
        self.open_img.setText(_translate("Form", "打开图像"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "123"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "456"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.open_win2.setText(_translate("Form", "打开窗口2"))
        self.close_win2.setText(_translate("Form", "关闭窗口2"))
        self.comboBox.setItemText(0, _translate("Form", "1"))
        self.comboBox.setItemText(1, _translate("Form", "2"))
        self.comboBox.setItemText(2, _translate("Form", "3"))
        self.comboBox.setItemText(3, _translate("Form", "4"))
        __sortingEnabled = self.ListWidget.isSortingEnabled()
        self.ListWidget.setSortingEnabled(False)
        item = self.ListWidget.item(0)
        item.setText(_translate("Form", "1"))
        item = self.ListWidget.item(1)
        item.setText(_translate("Form", "2"))
        item = self.ListWidget.item(2)
        item.setText(_translate("Form", "3"))
        self.ListWidget.setSortingEnabled(__sortingEnabled)
        self.emitS.setText(_translate("Form", "触发自定义信号"))
from qfluentwidgets import LineEdit, ListWidget, PrimaryPushButton, PushButton, SearchLineEdit
import source_rc
