# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'one.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(694, 488)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/icons/win_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("")
        self.pushButton = PushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.cBox = QtWidgets.QCheckBox(Form)
        self.cBox.setGeometry(QtCore.QRect(80, 100, 81, 21))
        self.cBox.setChecked(True)
        self.cBox.setObjectName("cBox")
        self.cBox_2 = QtWidgets.QCheckBox(Form)
        self.cBox_2.setGeometry(QtCore.QRect(100, 10, 51, 21))
        self.cBox_2.setObjectName("cBox_2")
        self.label_img = QtWidgets.QLabel(Form)
        self.label_img.setGeometry(QtCore.QRect(200, 10, 441, 441))
        self.label_img.setStyleSheet("background-image:url(:/assets/imgs/a123.png)")
        self.label_img.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img.setText("")
        self.label_img.setScaledContents(False)
        self.label_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img.setWordWrap(False)
        self.label_img.setObjectName("label_img")
        self.open_img = QtWidgets.QPushButton(Form)
        self.open_img.setGeometry(QtCore.QRect(30, 170, 81, 31))
        self.open_img.setObjectName("open_img")
        self.lineEdit = LineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 270, 113, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        self.cBox.toggled['bool'].connect(self.pushButton.setVisible) # type: ignore
        self.cBox.toggled['bool'].connect(self.cBox_2.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "第一个基于PyQt5的桌面应用"))
        self.pushButton.setText(_translate("Form", "关闭窗口"))
        self.cBox.setText(_translate("Form", "显示/隐藏"))
        self.cBox_2.setText(_translate("Form", "不可用"))
        self.open_img.setText(_translate("Form", "打开图像"))
from qfluentwidgets import LineEdit, PushButton
import source_rc
