# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'two.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(482, 310)
        font = QtGui.QFont()
        font.setPointSize(11)
        Form2.setFont(font)
        self.ProgressRing = ProgressRing(Form2)
        self.ProgressRing.setGeometry(QtCore.QRect(10, 80, 100, 100))
        self.ProgressRing.setObjectName("ProgressRing")
        self.DateEdit = DateEdit(Form2)
        self.DateEdit.setGeometry(QtCore.QRect(190, 110, 169, 33))
        self.DateEdit.setObjectName("DateEdit")
        self.Pivot = Pivot(Form2)
        self.Pivot.setGeometry(QtCore.QRect(0, 240, 210, 44))
        self.Pivot.setObjectName("Pivot")
        self.ZhDatePicker = ZhDatePicker(Form2)
        self.ZhDatePicker.setGeometry(QtCore.QRect(160, 150, 240, 30))
        self.ZhDatePicker.setObjectName("ZhDatePicker")
        self.CalendarPicker = CalendarPicker(Form2)
        self.CalendarPicker.setGeometry(QtCore.QRect(210, 190, 141, 31))
        self.CalendarPicker.setObjectName("CalendarPicker")
        self.ListWidget = ListWidget(Form2)
        self.ListWidget.setGeometry(QtCore.QRect(410, 80, 61, 161))
        self.ListWidget.setObjectName("ListWidget")
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        self.NavigationPanel = NavigationPanel(Form2)
        self.NavigationPanel.setGeometry(QtCore.QRect(0, 0, 51, 51))
        self.NavigationPanel.setProperty("menu", True)
        self.NavigationPanel.setObjectName("NavigationPanel")
        self.pushButton = QtWidgets.QPushButton(Form2)
        self.pushButton.setGeometry(QtCore.QRect(380, 0, 101, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "Form"))
        __sortingEnabled = self.ListWidget.isSortingEnabled()
        self.ListWidget.setSortingEnabled(False)
        item = self.ListWidget.item(0)
        item.setText(_translate("Form2", "1"))
        item = self.ListWidget.item(1)
        item.setText(_translate("Form2", "2"))
        item = self.ListWidget.item(2)
        item.setText(_translate("Form2", "3"))
        item = self.ListWidget.item(3)
        item.setText(_translate("Form2", "4"))
        item = self.ListWidget.item(4)
        item.setText(_translate("Form2", "5"))
        item = self.ListWidget.item(5)
        item.setText(_translate("Form2", "6"))
        self.ListWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("Form2", "点我也没用"))
from qfluentwidgets import CalendarPicker, DateEdit, ListWidget, NavigationPanel, Pivot, ProgressRing, ZhDatePicker
